<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__id</name>
   <tag></tag>
   <elementGuidId>bda7a312-4c6a-4ab5-be45-d4b6739280af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fcab40f-77ad-41d1-9f16-9e48e883b6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>223e15c9-0a10-4375-96c7-0902e73cf0b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>39e263fa-afe8-488c-a3f7-781443ddaf2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-dialog__content v-dialog__content--active&quot;]/div[@class=&quot;v-dialog v-dialog--active v-dialog--persistent v-dialog--fullscreen&quot;]/div[@class=&quot;v-card v-sheet theme--light rounded-0&quot;]/form[@class=&quot;v-form&quot;]/div[@class=&quot;v-card__text&quot;]/div[@class=&quot;v-input v-input--is-focused v-input--dense theme--light v-text-field v-text-field--is-booted v-text-field--enclosed v-text-field--outlined primary--text&quot;]/div[@class=&quot;v-input__control&quot;]/div[@class=&quot;v-input__slot&quot;]/div[@class=&quot;v-text-field__slot&quot;]/input[@id=&quot;id&quot;]</value>
      <webElementGuid>83923fe6-2583-4c0f-857e-9f725bcd73e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id']</value>
      <webElementGuid>c0f081b6-81db-4d34-975f-3ecfd1a641e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/form/div[2]/div/div/div/div/input</value>
      <webElementGuid>72804525-696a-4414-a22d-a19a9648fd20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>cfadb8e1-44a7-4194-8d0a-656e7239e59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id' and @type = 'text']</value>
      <webElementGuid>4914a44c-49b1-4029-8cf2-8ef8a7e5513b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
