<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-34</name>
   <tag></tag>
   <elementGuidId>46383b6d-502b-4bca-9120-086420b15c8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-34</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-34']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>892a37ba-6d94-4b7f-9592-73e2250c3063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-34</value>
      <webElementGuid>c16f7be9-dfc8-4a3a-a473-e872c2ba6caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc6b304e-f323-43dc-8577-8d123292dda0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-34&quot;)</value>
      <webElementGuid>8ba22ee0-c457-4e1a-afdf-dc285cb31359</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-34']</value>
      <webElementGuid>da98a8b9-be67-45f5-b50a-7ca5387587dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/form/div/div/div/div/input</value>
      <webElementGuid>1d2c82ed-bb41-4315-855e-4d74544f04c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ff1d96bf-1a37-4c7d-9b10-dbd8f992a777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-34' and @type = 'text']</value>
      <webElementGuid>ec9d2f2b-8dd7-4437-986a-c78384205aeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
