<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-37</name>
   <tag></tag>
   <elementGuidId>4351fe52-69a4-46cc-a9d9-731da62f54b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-37</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-37']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fb669b5-bcec-4f7f-9394-d7dbdbf85505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-37</value>
      <webElementGuid>78b9f0f2-b002-4d6d-b262-e37d3a021805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>9bb7fd36-031b-4daf-baef-83d96fb46995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-37&quot;)</value>
      <webElementGuid>ffedc867-1de1-46d0-90e2-12cdf35f6ecb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-37']</value>
      <webElementGuid>6a2270e4-1ae3-4304-a048-23afc185bf39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/form/div[2]/div/div/div/input</value>
      <webElementGuid>ef63dd66-3335-4d65-b5f3-f09d568f1629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>3e5ad0e3-470c-4ac7-82f9-627b3024beb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-37' and @type = 'password']</value>
      <webElementGuid>e80519d1-7bde-4af2-a3d5-5b1d35549602</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
