<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-23</name>
   <tag></tag>
   <elementGuidId>e4b49f3b-1ccc-4f92-814c-e1e5c6676868</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-23</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-23']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d981d0f-a92b-47c3-b66a-150718ddbda0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-23</value>
      <webElementGuid>4046fcfb-127a-439e-9e1a-862a2a98b75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8b5d865-599b-44d9-997d-dd5433fa4c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-23&quot;)</value>
      <webElementGuid>2511fceb-3e12-4a28-aff9-7b1864b32fbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-23']</value>
      <webElementGuid>70c49c52-c07f-482a-84e5-602351a4d1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/form/div/div/div/div/input</value>
      <webElementGuid>409119ae-2572-4039-9217-c71a136bd6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a16f4bc1-0a5a-4f90-9450-2bc98b8d7a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-23' and @type = 'text']</value>
      <webElementGuid>8659a143-b52b-4fc9-95dc-f4ecfe4aac6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
